- hosts: hadoops
  remote_user: root
  tasks:
    - name: Disable SELinux at next reboot
      selinux:
        state: disabled

    - name: disable firewalld
      shell: "{{ item }}"
      with_items:
         - systemctl stop firewalld
         - systemctl disable firewalld
         - echo "vm.swappiness = 0" >> /etc/sysctl.conf
         - swapoff -a
         - sysctl -w vm.swappiness=0

    - name: timedatectl
      shell: "{{ item }}"
      with_items:
        - timedatectl set-timezone Asia/Shanghai
        - timedatectl set-ntp true
        - hwclock -w

    - name: install-epel
      shell: "{{ item }}"
      with_items:
        - yum install -y epel-release

    - name: install-basic
      shell: "{{ item }}"
      with_items:
        - yum install -y zip unzip lrzsz git wget htop chrony deltarpm gcc gcc-c++ pcre pcre-devel zlib zlib-devel openssl openssl-devel

    - name: copy chrony.conf
      copy:
        src=/etc/chrony.conf
        dest=/etc/chrony.conf.back

    - name: remove chrony.conf
      file:
        path: /etc/chrony.conf
        state: absent

    - name: create chrony.conf
      file:
        path=/etc/{{ item }}
        state=touch
        mode=777
      with_items:
        - chrony.conf

    - name: set chrony.conf
      blockinfile:
        path: /etc/chrony.conf
        marker: ""
        block: |
          server ntp1.aliyun.com minpoll 4 maxpoll 10 iburst
          server ntp2.aliyun.com minpoll 4 maxpoll 10 iburst
          server ntp3.aliyun.com minpoll 4 maxpoll 10 iburst
          server ntp4.aliyun.com minpoll 4 maxpoll 10 iburst
          server ntp5.aliyun.com minpoll 4 maxpoll 10 iburst
          server ntp6.aliyun.com minpoll 4 maxpoll 10 iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony

- name: chronyd enable
    shell: "{{ item }}"
    with_items:
      - systemctl restart chronyd.service
      - systemctl enable chronyd.service


    - name: install-vim
      shell: "{{ item }}"
      with_items:
         - yum install -y vim
         - curl https://gitee.com/cdk8s_org/vim-for-server/raw/master/vimrc > ~/.vimrc
