- hosts: hadoops
  remote_user: root
  vars:
    install_folder: "/usr/local"
    zookeeper_home_path: "{{ install_folder }}/apache-zookeeper-3.5.7-bin"
  tasks:
    - name: echo JAVA_HOME
      debug:
        msg: "'{{ lookup('env', 'JAVA_HOME') }}' -- is environment variable"

    - name: get environment variable JAVA_HOME
      set_fact:
        JAVA_HOME_VAR: "{{ lookup('env', 'JAVA_HOME')}}"
    - name: check JAVA_HOME environment variable
      fail:
        msg: "Environment variable JAVA_HOME is not defined or empty"
      when: JAVA_HOME_VAR == ""

    - name: check zookeeper folders exist
      stat:
        path: "{{ zookeeper_home_path }}"
      register: register_result
    - name: check zookeeper folders exist fail
      fail:
        msg: "check zookeeper folders exist fail"
      when: not register_result.stat.exists
